from fastapi import APIRouter
from pydantic import BaseModel
from typing import List
import hashlib

router = APIRouter(prefix="/guard", tags=["EchoVault Guard"])

class PasswordCheck(BaseModel):
    password_hash: str

class DomainCheck(BaseModel):
    domain: str

class AssetUpload(BaseModel):
    emails: List[str] = []
    domains: List[str] = []
    apis: List[str] = []

import time
# In-memory store for demo real-time logs crossing from extension to dashboard
RECENT_ALERTS = []

# Generate a large dataset of potential risk passwords dynamically
bad_passwords = ["password", "password123", "admin", "root", "12345"]

# Add repeated integers (e.g. 111111, 2222222)
for i in range(10):
    for length in range(3, 15):
        bad_passwords.append(str(i) * length)

# Add consecutive strings and descending numbers
bad_passwords.extend([
    "12345", "123456", "1234567", "12345678", "123456789", "1234567890",
    "987654321", "987654", "0123456789",
    "qwerty", "qwertyuiop", "qazwsx", "asdfgh", "asdfghjkl", "zxcvbnm",
    "abcdef", "abcdefg", "abcdefgh", "123123", "password1234"
])

try:
    from pybloom_live import BloomFilter
    # Simulate a production RedisBloom / PyBloom filter loaded with millions of hashes
    bloom = BloomFilter(capacity=1000000, error_rate=0.001)
    
    # Adding known bad test hashes dynamically
    for pw in bad_passwords:
        bloom.add(hashlib.sha256(pw.encode()).hexdigest())
except ImportError:
    bloom = [hashlib.sha256(pw.encode()).hexdigest() for pw in bad_passwords]

@router.post("/check-password")
async def check_password(req: PasswordCheck):
    """Zero-Knowledge Password Verification Layer."""
    if req.password_hash in bloom:
        return {"status": "leaked", "risk": "critical"}
    return {"status": "safe", "risk": "low"}

@router.post("/check-domain")
async def check_domain(req: DomainCheck):
    """Predictive Risk Scoring for Dark Web / General Domains via ML Simulation."""
    domain_lower = req.domain.lower()
    
    # Simple simulated heuristic for ML probabilities
    if "market" in domain_lower or "hub" in domain_lower or "leak" in domain_lower:
        alert_msg = f"[EXTENSION] 🛑 BLOCKED NAVIGATION: User attempted access to high-risk malicious domain '{req.domain}'"
        RECENT_ALERTS.append({"timestamp": time.time(), "message": alert_msg})
        return {
            "risk_score": 91, 
            "risk_level": "critical", 
            "reason": "credential harvesting marketplace detected via semantic NLP inference"
        }
    elif "forum" in domain_lower:
        alert_msg = f"[EXTENSION] ✅ ALLOWED NAVIGATION: User accessed moderate-risk domain '{req.domain}'"
        RECENT_ALERTS.append({"timestamp": time.time(), "message": alert_msg})
        return {
            "risk_score": 65, 
            "risk_level": "moderate", 
            "reason": "high volume of unregulated PII trading expected"
        }
        
    alert_msg = f"[EXTENSION] ✅ ALLOWED NAVIGATION: User accessed low-risk domain '{req.domain}'"
    RECENT_ALERTS.append({"timestamp": time.time(), "message": alert_msg})
    return {
        "risk_score": 10, 
        "risk_level": "low", 
        "reason": "clean reputation score across all threat feeds"
    }

@router.post("/upload-assets")
async def upload_assets(assets: AssetUpload):
    """Uploads customer asset footprints into the ShadowPulse RedisBloom structure."""
    total = sum(len(x) for x in [assets.emails, assets.domains, assets.apis])
    # In production, these hashes are dispatched to Redis clusters.
    return {"status": "assets protected", "assets_tracked": total}

@router.get("/recent-alerts")
async def get_recent_alerts(since: float = 0):
    """Fetch real-time alerts generated by the Guard extension."""
    new_alerts = [a for a in RECENT_ALERTS if a["timestamp"] > since]
    return {"alerts": new_alerts}
